export { default as Header } from "./header/header";
export { default as Form } from "./form/form";
export { default as QuizList } from "./quizlist/quizlist";
export { default as PrivateRoute } from "./privateroute/privateroute";
export { default as Timer } from "./timer/timer";
export { default as QuestionComponent } from "./question/questionComponent";
export { default as PrevButton } from "./question/prevButton";
export { default as FinishButton } from "./question/finishButton";
export { default as NextButton } from "./question/nextButton";
